[default.probe]
protocol = "Swd"

[default.flashing]
enabled = true
restore_unwritten_bytes = false

[default.reset]
enabled = true

[default.general]
chip = "STM32F303VCTx"
log_level = "WARN"
connect_under_reset = true

[default.rtt]
enabled = true
up_mode = "NoBlockSkip"

[default.gdb]
enabled = true
gdb_connection_string = "127.0.0.1:3333"
